name: Generate SBOM

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install CycloneDX Node.js module
        run: npm install -g @cyclonedx/bom

      - name: Install dependencies
        run: npm install

      - name: Generate SBOM
        run: cyclonedx-bom -o sbom.json

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json
